# Generated by Django 2.1.15 on 2022-09-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_auto_20220823_0953'),
        ('sitios', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviciossedes',
            unique_together={('sedesClinica', 'servicios')},
        ),
    ]
