# Generated by Django 2.1.15 on 2022-09-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_auto_20220901_1125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subserviciossedes',
            unique_together={('sedesClinica', 'servicios', 'subServicios')},
        ),
    ]
