# Generated by Django 2.1.15 on 2022-09-01 21:14

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0006_auto_20220901_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='servicios',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='serviciosSedes', chained_model_field='serviciosSedes', on_delete=django.db.models.deletion.CASCADE, related_name='dos', to='sitios.ServiciosSedes'),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='serviciosSedes',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='sedesClinica', chained_model_field='sedesClinica', on_delete=django.db.models.deletion.CASCADE, related_name='uno', to='sitios.ServiciosSedes'),
        ),
    ]
