# Generated by Django 2.1.15 on 2022-09-01 21:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0008_auto_20220901_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='subServicios',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='sedesClinica', chained_model_field='sedesClinica', on_delete=django.db.models.deletion.CASCADE, to='sitios.SubServiciosSedes'),
        ),
    ]
