# Generated by Django 2.1.15 on 2022-09-01 21:20

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0010_auto_20220901_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='subServicios',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='servicios', chained_model_field='servicios', on_delete=django.db.models.deletion.CASCADE, to='sitios.ServiciosSedes'),
        ),
    ]
