# Generated by Django 2.1.15 on 2022-09-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0011_auto_20220901_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='serviciosSedes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serviciosSedes1', to='sitios.ServiciosSedes'),
        ),
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('sedesClinica', 'serviciosSedes', 'subServicios', 'numero', 'dependenciasTipo')},
        ),
    ]
