# Generated by Django 2.1.15 on 2022-09-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0012_auto_20220901_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('sedesClinica', 'serviciosSedes', 'subServicios', 'servicios', 'numero', 'dependenciasTipo')},
        ),
    ]
