# Generated by Django 2.1.15 on 2022-09-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('nomenclatura', models.CharField(max_length=20)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ModulosElementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ModulosElementosDef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('modulosElementosId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.ModulosElementos')),
                ('modulosId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Modulos')),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilesClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilesClinicaOpciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('modulosElementosDefId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.ModulosElementosDef')),
                ('perfilesClinicaId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.PerfilesClinica')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilesOpciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('modulosElementosDefId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.ModulosElementosDef')),
                ('perfilesId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilesUsu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adicion', models.CharField(default='S', max_length=1)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('perfilesClinicaOpcionesId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.PerfilesClinicaOpciones')),
                ('plantaId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
    ]
