# Generated by Django 2.1.15 on 2022-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='logo',
            field=models.CharField(default='', max_length=120),
        ),
    ]
