# Generated by Django 3.2 on 2022-08-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['tipoDoc', 'documento', 'folio', 'fecha', 'especialidades', 'motivo', 'subjetivo', 'objetivo', 'analisis', 'plann']},
        ),
        migrations.RenameField(
            model_name='historia',
            old_name='plan',
            new_name='plann',
        ),
    ]
